config/routes.rb
Rails.application.routes.draw do
  get "dev/tables" => "web/tables#index", as: :web_tables
  get "dev/tables/:name" => "web/tables#show", as: :web_table
  resources :castings
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/web/tables_controller.rb
class Web::TablesController < ApplicationController
  # GET /web/tables
  # GET /web/tables.json
  def index
    @tables = ActiveRecord::Base.connection.tables.map do |x|
      x.classify.safe_constantize
    end.compact

    @most_columns = @tables.map { |t| t.columns.count }.max
  end

  # GET /web/tables/1
  # GET /web/tables/1.json
  def show
    @table = params[:name]
  end

  # GET /web/tables/new
  def new
    @web_table = Web::Table.new
  end

  # GET /web/tables/1/edit
  def edit
  end

  # POST /web/tables
  # POST /web/tables.json
  def create
    @web_table = Web::Table.new(web_table_params)

    respond_to do |format|
      if @web_table.save
        format.html { redirect_to @web_table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @web_table }
      else
        format.html { render :new }
        format.json { render json: @web_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web/tables/1
  # PATCH/PUT /web/tables/1.json
  def update
    respond_to do |format|
      if @web_table.update(web_table_params)
        format.html { redirect_to @web_table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @web_table }
      else
        format.html { render :edit }
        format.json { render json: @web_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web/tables/1
  # DELETE /web/tables/1.json
  def destroy
    @web_table.destroy
    respond_to do |format|
      format.html { redirect_to web_tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/web/tables_helper.rb
module Web::TablesHelper
end

app/views/web/tables/_form.html.erb
<%= form_with(model: web_table, local: true) do |form| %>
  <% if web_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web_table.errors.count, "error") %> prohibited this web_table from being saved:</h2>

      <ul>
      <% web_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/web/tables/edit.html.erb
<h1>Editing Web Table</h1>

<%= render 'form', web_table: @web_table %>

<%= link_to 'Show', @web_table %> |
<%= link_to 'Back', web_tables_path %>

app/views/web/tables/index.html.erb
<h1>
  All tables
</h1>

<hr>

<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <thead class="thead-inverse">
      <th>
        Table
      </th>

      <th colspan="<%= @most_columns %>">
        Columns
      </th>
    </thead>

    <tbody>
      <% @tables.each do |table| %>
      <tr>
        <th>
          <%= link_to table, web_table_path(table) %>
        </th>

        <% table.columns.each do |column| %>
        <td>
          <%= column.name %>
        </td>
        <% end %>

        <% (@most_columns - table.columns.count).times do %>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<p class="lead">
  What would you like to do?
</p>

<div class="btn-group-vertical btn-block">
  <a href="#" class="btn btn-secondary">
    Add a new table (only model, first:scaffold, scaffold, etc)
  </a>

  <a href="#" class="btn btn-secondary">
    Drop a table (destroy a whole scaffold?)
  </a>
</div>

app/views/web/tables/new.html.erb
<h1>New Web Table</h1>

<%= render 'form', web_table: @web_table %>

<%= link_to 'Back', web_tables_path %>

app/views/web/tables/show.html.erb
<h1>
  <%= @table %>

</h1>

<%= link_to "Back", web_tables_path %>

<hr>

<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <thead class="thead-inverse">
      <th>Name</th>
      <th>SQL Type</th>
      <th>Default</th>
      <th>Type</th>
      <th>Limit</th>
      <th>Null</th>
      <th>Precision</th>
      <th>Scale</th>
    </thead>

    <tbody>
      <% @table.classify.safe_constantize.columns.each do |column| %>
      <tr>
        <td>
          <%= column.name	 %>
        </td>

        <td>
          <%= column.sql_type	 %>
        </td>

        <td>
          <%= column.default	 %>
        </td>

        <td>
          <%= column.type	 %>
        </td>

        <td>
          <%= column.limit	 %>
        </td>

        <td>
          <%= column.null	 %>
        </td>

        <td>
          <%= column.precision	 %>
        </td>

        <td>
          <%= column.scale	 %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<p class="lead">
  What would you like to do?
</p>

<div class="btn-group-vertical btn-block">
  <a href="#" class="btn btn-secondary">
    Add a column (foreign key, reference)
  </a>

  <a href="#" class="btn btn-secondary">
    Drop a column
  </a>

  <a href="#" class="btn btn-secondary">
    Rename a column
  </a>

  <a href="#" class="btn btn-secondary">
    Add a default value for a column
  </a>

  <a href="#" class="btn btn-secondary">
    Add an index to a column
  </a>

  <a href="#" class="btn btn-secondary">
    Drop the whole table
  </a>
</div>